### ISSUE TITLE
request command line options

### ISSUE THREAD

**Issue by FEBuilderGBA** [Kermalis/VGMusicStudio#81]
I have request.
I want you to support command line options.

//Play SongID 123 (0x7B) from ROMNAME.gba.
VGMusicStudio.exe --play=123 --engine=mp2k ROMNAME.gba
or
VGMusicStudio.exe --play=123 --engine=mp2k --filename=ROMNAME.gba

If possible, also want to be able to specify the address of the SongTable.
VGMusicStudio.exe --songtable=0x08123450 --play=123 --engine=mp2k --filename=ROMNAME.gba

I think command line options make it easier to work with other tools.

**Comment by Kermalis** [comment]
Hi, I like this idea but how would the last one be useful? Wouldn't it make more sense to add it to the config, since the config has all of the necessary info to run?

The old version had a way to support multiple songtables, but this one cannot for now. For now you'll need copies of the config with each table. Is that what the goal is?

**Comment by FEBuilderGBA** [comment]
>The old version had a way to support multiple songtables, but this one cannot for now. For now you'll need copies of the config with each table. Is that what the goal is?

I see.
Then I don't need the --songtable option.

I was thinking of it as a remedy if there was a ROM that couldn't recognize the song table.
The current VGMusicStudio seems to automatically recognize the song table, so it's not needed.

I would like to request the implementation of this function.
VGMusicStudio.exe --play=123 --engine=mp2k --filename=ROMNAME.gba

**Comment by FEBuilderGBA** [comment]
This may be another suggestion, but I would like to add a supplement.

MP2K.yaml
```
BE8J_00:
  Name: "Fire Emblem: The Sacred Stones (Japan)"
  SongTableOffsets: 0x214120
  Copy: "BE8E_00"
```

For example, FE8J is currently defined this way.
Basically this is fine, but with HackROM, SongTable may be repointed.
(Such works are rare, but they are possible.)

I have the code to automatically track the SongTable on the MP2K(M4A) Engine.
https://github.com/FEBuilderGBA/FEBuilderGBA/blob/master/FEBuilderGBA/SongExchangeForm.cs#L169

With this code you can find the Song Tabe for most games.
This code can automatically track the repoint destination even if the SongTable is repointed.

I think it would be more convenient if SongTable could be tracked automatically instead of getting an error when SongTable doesn't exist in the database written in MP2K.yaml or when it doesn't exist in the database.

If you can specify SongTable as an argument on the command line, you can handle such cases.
Or, if can't find the SongTable in the yaml database, it would be easier for the user to install a function that automatically finds the SongTable like sappy.

**Comment by Kermalis** [comment]
Songtable detecting is something I've gotten requested a lot, but I won't be implementing it for a while and don't think it should be necessarily. Like I said, you can have copies of the config with the correct offsets for romhacks (and romhacks should be using custom game codes [or game revision] anyway, which you can add to the config already)

This is why I think the rest is a good idea but the song table detection is not. I've had romhacks with more than one songtable, but that's a mess to implement, which is why I haven't added that back to the new version. Also, some games like mother use two different "engines" for each game, which I've seen what I can do about but it's just a horrible thing. Multiple configs is not the cleanest, but it's 1000x easier to use, and doesn't add a bunch of bloat to the program for very rare edge cases like these.

**Comment by FEBuilderGBA** [comment]
I see.
Thank you.

Thanks also to Dassu for implementing the option.
