### ISSUE TITLE
App does not have a global volume setting

### ISSUE THREAD

**Issue by citrusui** [Kermalis/VGMusicStudio#89]
Certain songs, such as BGM_JUNGLE from Kirby: Mass Attack (SDAT Engine) exceed the maximum volume and start clipping. The current VG Music Studio does not prevent this, even in playlist mode, as the volume slider only affects the sound after it has been sequenced, mixed, and down-sampled to 16-bit, 65.4KHz stereo audio.

There is also no way to open the Track Viewer to change the volume parameters of tracks -- all parameters are read-only. Implementing such a feature is a different task, but could theoretically prevent clipping from occurring.

**Comment by Kermalis** [comment]
I just checked, and that song is clipping, but not by much
![image](https://user-images.githubusercontent.com/29823718/123988062-b0882900-d995-11eb-8cc9-28a97f3c0850.png)

Are you sure the game doesn't clip normally? I use the same volume parameters from the sdat player as the game would.

**Comment by citrusui** [comment]
Thanks for the quick reply.

"Not by much" seems to be... a subjective term. 

![image](https://user-images.githubusercontent.com/9056756/123989668-1cb75c80-d997-11eb-93b1-141e3c00b42c.png)

I do think the track normally clips, but even so, it's something that can be fixed. I believe the VGMS mixer internally uses float, correct? Perhaps the volume can be set (user-configurable) to turn down the song before the sample-depth conversion to 16-bit.

**Comment by Kermalis** [comment]
Well SDAT and DSE don't use floats internally anymore, they just use pcm16 the whole time. I know the DS uses something other than pcm16 but it's not complete yet, and I'm aware of some other songs clipping.

I left it as is before because this program's goal is accuracy. There are so many other players out there that can make each engine sound better in different ways, from interpolation to float to this kind of scenario.

I also made the volume slider affect the final output only, for that same reason. So that would be considered the "speaker volume" on your handheld

So I feel like it should be left as is, just because of the premise behind this program, if the original clips the same way. I know the mixer isn't 100% accurate (none of them are yet) but I think it should be as close as possible, since this is the only tool going for accuracy anymore, that I'm aware of.

Someone in my Discord has used VGMS's code and made their own SDAT player, so perhaps you can ask them if their tool can fix clipping, since their tool is just a general SDAT player with some tweaks

Maybe one day in the future I can have plugin support that can add this kind of tweak without it being a mandatory feature for everyone. I thought about plugins for a while now, since many people ask for obscure formats that I don't have time to add. Other formats would be better as part of the program than as a plugin, but stuff that alters the audio I feel should be a plugin, kinda like how foobar2000 does it.

Sorry if that's not the answer you wanted
