### ISSUE TITLE
[MP2K][Bug Report] Tune calculation when saving to MIDI

### ISSUE THREAD

**Issue by laqieer** [Kermalis/VGMusicStudio#99]
https://github.com/Kermalis/VGMusicStudio/pull/98/commits/5a85cda7b5896639f38691b2ea7e52046e8daddc

**Comment by Kermalis** [comment]
Hi, does this still keep the MIDIs matching? As in, does the midi produce a matching asm output with mid2agb?

The current midi exporter matched all MIDIs for the 5 main series Pokémon games, so as long as this tune modification is an actual fix then it's accepted. I don't remember if they used tune at the moment

Other enhancements to the midi exporter won't be accepted right now since there's no way to toggle the output type (matching or enhanced) with a dialog

**Comment by laqieer** [comment]
The expoted midi doesn't match without the bug fix. As in, it produces a mismatching asm output with mid2agb.

Here is an example: https://github.com/FireEmblemUniverse/fireemblem8u/pull/137/commits/4b87e799dc9af630cc6b952bb9b61ebe68357431

**Comment by Kermalis** [comment]
Hey, I was just making sure it still matches, thanks for the proof. I just didn't remember if the 5 Pokémon games used TUNE or not.

If you make a PR for this commit I'll accept it right away. Your other PR I haven't looked at yet, since I've been so busy irl, but thankfully someone else is helping review it

**Comment by Kermalis** [comment]
Closed in #100
